### PR TITLE
Dynamic color

### PR DESCRIPTION
**Pull request by Djhranicky**
Implemented a basic form of the algorithm that makes a gradient from red -> yellow -> green. Attempts to standardize the scores right before creating the color. When standardized scores between different metrics get implemented, that can be switched in

### CODE REVIEW

**Comment by Djhranicky** [comment]
I think gui should be pr'd before this goes in. Currently trying to fix gui but the issue runs deep and saw how to implement this quite easily

**Comment by TBean18** [comment]
> I think gui should be pr'd before this goes in. Currently trying to fix gui but the issue runs deep and saw how to implement this quite easily

Didn't you just PR the GUI branch into main today?

**Comment by Djhranicky** [comment]
I reverted it so it can be done properly when the gui is fully functional

**Review by Armintron — CHANGES_REQUESTED** [review]
`wordScoreMap` will no longer be used if we adopt this approach. It and other related code should be removed.

**Comment by Armintron** [comment]
Features have already been implemented

**Pull request closed without merging**
