### PR TITLE
Adds optional phonetic encoding to GUI and thread number selection

### PR DESCRIPTION
**Pull request by Armintron**
There are also some miscellaneous changes to the GUI such as adding tooltips to interactable fields and adjusting the length of the search word entry

image

### CODE REVIEW

**Review by Djhranicky — CHANGES_REQUESTED** [review]
DoubleMetaphone is broken. 

If the number box is for the number of threads, there needs to be something on the GUI saying so

**Comment by Armintron** [comment]
> DoubleMetaphone is broken.
> 
> If the number box is for the number of threads, there needs to be something on the GUI saying so

null check now prevents this, but doublemetaphone still seems to not give useful results. We can leave it in for now and debug the algorithm itself later.

**Comment by Armintron** [comment]
Now has a label for the thread count

image

**Review by Djhranicky — APPROVED** [review]
Lgtm, great work!

**Review by TBean18 — APPROVED** [review]
lgtm! 👍 The only nitpicky thing I thought about is that we could add the dropdown tooltips inside of the dropDownHandler class instead of in main but that is purely stylistic. Additionally, the other tooltips are assigned for non-dropdown elements in main so probably best to keep them all together.

**Comment by Armintron** [comment]
> lgtm! 👍 The only nitpicky thing I thought about is that we could add the dropdown tooltips inside of the dropDownHandler class instead of in main but that is purely stylistic. Additionally, the other tooltips are assigned for non-dropdown elements in main so probably best to keep them all together.

I agree with both statements.

**Pull request merged**
